version: "3"

services:
 nginx:
      container_name: nginx
      build: ./requirements/nginx/
      image: nginx:v1
      hostname: beaudibe.42.fr
      ports:
         - "443:443"
      volumes:
         - wordpress_code:/var/www/wordpress/ 
      env_file:
         - .env
      networks:
         - inception-network
      restart: always
      depends_on:
            - wordpress
 wordpress:
      container_name: wordpress
      hostname: wordpress
      build: ./requirements/wordpress/
      image: wordpress:v1
      volumes:
         - wordpress_code:/var/www/wordpress/
      expose:
         - "9000"
      networks:
         - inception-network
      env_file:
         - .env
      restart: always
      depends_on:
         - db
 db:
      container_name: mariadb
      build:
         context: ./requirements/mariadb/
         args:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      image: mariadb:v1
      volumes:
         - wordpress_db:/var/lib/mysql/$MYSQL_DATABASE
      expose:
         - "3306"
      env_file:
         - .env
      networks:
         - inception-network
      restart: always
      hostname: "db"

volumes:
 wordpress_code:
      driver: local
      driver_opts:
         type: none
         device: $HOME/beaudibe/data/wordpress_code/
         o: bind
 wordpress_db:
      driver: local
      driver_opts:
         type: none
         device: $HOME/beaudibe/data/wordpress_db/
         o: bind

networks:
      inception-network:
            name: inception-network
            driver: bridge
