FROM debian:bullseye

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y nginx openssl


# ENV PORT=8080

# EXPOSE 8080

WORKDIR /etc/nginx/

RUN 	mkdir -p /etc/nginx/pop
RUN 	mkdir -p /etc/nginx/ssl

RUN		openssl req \
		-x509 \
		-nodes \
		-days 365 \
		-newkey rsa:2048 \
		-keyout /etc/nginx/ssl/nginx.key \
		-out /etc/nginx/ssl/nginx.crt -subj '/CN=beaudibe.42.fr'

RUN		rm -f /etc/nginx/conf.d/default.conf
RUN		rm -f /etc/nginx/sites-enabled/default

COPY	conf/wp.conf	/etc/nginx/conf.d/wp.conf
COPY	conf/nginx.conf	/etc/nginx/nginx.conf
#COPY	conf/hello.html	/etc/nginx/pop/hello.html


ENTRYPOINT ["nginx", "-g", "daemon off;"]

